name: Create OCT's container image for the new release

on:
  release:
    types: [published]

env:
  TERM: xterm-color
  REGISTRY: quay.io/testnetworkfunction
  REPO: oct
  VERSION: ${{ github.ref_name }}
  IMAGE_TAG: ${REGISTRY}/${REPO}:${VERSION}

jobs:
  create-oct-container-image:
    name: Create new OCT container image
    runs-on: ubuntu-20.04
    env:
      SHELL: /bin/bash

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
        with:
          ref: main
          token: ${{ secrets.PULL_TOKEN }}

      - name: Show version and full release tag
        run: |
          echo "Version: ${VERSION}. Full image tag: ${IMAGE_TAG}"

      - name: Build OCT container image
        run: |
          docker build -t ${IMAGE_TAG} --build-arg TOKEN=${{ secrets.PULL_TOKEN }} --no-cache .

      - name: Authenticate against Quay.io
        uses: docker/login-action@v3
        with:
          registry: quay.io
          # Use a Robot Account to authenticate against Quay.io
          # https://docs.quay.io/glossary/robot-accounts.html
          username: ${{ secrets.QUAY_ROBOT_USER }}
          password: ${{ secrets.QUAY_ROBOT_TOKEN }}

      - name: Push the newly built image to Quay.io
        run: docker push ${IMAGE_TAG}
